name: "Java CI"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: jjjj
        uses: ./.github/actions/run-maven
        with:
          java-version: "21"
